// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-services.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterAccountRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountRequest) Reset()         { *m = RegisterAccountRequest{} }
func (m *RegisterAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountRequest) ProtoMessage()    {}
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{0}
}

func (m *RegisterAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountRequest.Unmarshal(m, b)
}
func (m *RegisterAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountRequest.Merge(m, src)
}
func (m *RegisterAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountRequest.Size(m)
}
func (m *RegisterAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountRequest proto.InternalMessageInfo

func (m *RegisterAccountRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterAccountResponse struct {
	Code                 string               `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponseAccount `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterAccountResponse) Reset()         { *m = RegisterAccountResponse{} }
func (m *RegisterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountResponse) ProtoMessage()    {}
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{1}
}

func (m *RegisterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountResponse.Unmarshal(m, b)
}
func (m *RegisterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountResponse.Merge(m, src)
}
func (m *RegisterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountResponse.Size(m)
}
func (m *RegisterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountResponse proto.InternalMessageInfo

func (m *RegisterAccountResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RegisterAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegisterAccountResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterAccountResponse) GetData() *DataResponseAccount {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponseAccount struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponseAccount) Reset()         { *m = DataResponseAccount{} }
func (m *DataResponseAccount) String() string { return proto.CompactTextString(m) }
func (*DataResponseAccount) ProtoMessage()    {}
func (*DataResponseAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{2}
}

func (m *DataResponseAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponseAccount.Unmarshal(m, b)
}
func (m *DataResponseAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponseAccount.Marshal(b, m, deterministic)
}
func (m *DataResponseAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponseAccount.Merge(m, src)
}
func (m *DataResponseAccount) XXX_Size() int {
	return xxx_messageInfo_DataResponseAccount.Size(m)
}
func (m *DataResponseAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponseAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponseAccount proto.InternalMessageInfo

func (m *DataResponseAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LoginRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 string             `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponseLogin `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LoginResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetData() *DataResponseLogin {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponseLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	LoggedTime           string   `protobuf:"bytes,4,opt,name=loggedTime,proto3" json:"loggedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponseLogin) Reset()         { *m = DataResponseLogin{} }
func (m *DataResponseLogin) String() string { return proto.CompactTextString(m) }
func (*DataResponseLogin) ProtoMessage()    {}
func (*DataResponseLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{5}
}

func (m *DataResponseLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponseLogin.Unmarshal(m, b)
}
func (m *DataResponseLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponseLogin.Marshal(b, m, deterministic)
}
func (m *DataResponseLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponseLogin.Merge(m, src)
}
func (m *DataResponseLogin) XXX_Size() int {
	return xxx_messageInfo_DataResponseLogin.Size(m)
}
func (m *DataResponseLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponseLogin.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponseLogin proto.InternalMessageInfo

func (m *DataResponseLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DataResponseLogin) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *DataResponseLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DataResponseLogin) GetLoggedTime() string {
	if m != nil {
		return m.LoggedTime
	}
	return ""
}

type DataRequest struct {
	Hello                string   `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{6}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

type DataResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{7}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterAccountRequest)(nil), "v1.RegisterAccountRequest")
	proto.RegisterType((*RegisterAccountResponse)(nil), "v1.RegisterAccountResponse")
	proto.RegisterType((*DataResponseAccount)(nil), "v1.DataResponseAccount")
	proto.RegisterType((*LoginRequest)(nil), "v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "v1.LoginResponse")
	proto.RegisterType((*DataResponseLogin)(nil), "v1.DataResponseLogin")
	proto.RegisterType((*DataRequest)(nil), "v1.DataRequest")
	proto.RegisterType((*DataResponse)(nil), "v1.DataResponse")
}

func init() { proto.RegisterFile("user-services.proto", fileDescriptor_40c6cf8152457cbc) }

var fileDescriptor_40c6cf8152457cbc = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x75, 0x49, 0xfa, 0xeb, 0xb5, 0x55, 0xd3, 0x6b, 0x69, 0xa3, 0x80, 0x90, 0x65, 0x24,
	0x54, 0x02, 0x8e, 0x9b, 0xb4, 0x48, 0x28, 0x2c, 0x14, 0x90, 0x58, 0x98, 0x0c, 0x48, 0x0c, 0x2c,
	0x17, 0xfb, 0xe9, 0x72, 0xad, 0x73, 0x67, 0xee, 0xce, 0x29, 0x6c, 0x80, 0x18, 0x99, 0x60, 0xe3,
	0x4f, 0x62, 0x65, 0x61, 0x60, 0xe4, 0x0f, 0x41, 0xfe, 0x91, 0x12, 0x27, 0x65, 0xeb, 0x14, 0x7f,
	0xdf, 0x7b, 0x97, 0xcf, 0x7b, 0x5f, 0x3f, 0x1f, 0xec, 0xa4, 0x06, 0xb5, 0x67, 0x50, 0x4f, 0x44,
	0x88, 0xa6, 0x9b, 0x68, 0x65, 0x15, 0xad, 0x4d, 0x7a, 0xed, 0x1b, 0x5c, 0x29, 0x1e, 0xa3, 0xcf,
	0x12, 0xe1, 0x33, 0x29, 0x95, 0x65, 0x56, 0x28, 0x59, 0x56, 0xb4, 0xef, 0xe5, 0x3f, 0xa1, 0xc7,
	0x51, 0x7a, 0xe6, 0x9c, 0x71, 0x8e, 0xda, 0x57, 0x49, 0x5e, 0xb1, 0x58, 0xed, 0x0e, 0x61, 0x2f,
	0x40, 0x2e, 0x8c, 0x45, 0x7d, 0x12, 0x86, 0x2a, 0x95, 0x36, 0xc0, 0xb7, 0x29, 0x1a, 0x4b, 0x9b,
	0x50, 0x67, 0x89, 0x68, 0x11, 0x87, 0x1c, 0xac, 0x05, 0xd9, 0x23, 0x6d, 0xc3, 0x6a, 0xd6, 0x92,
	0x64, 0x63, 0x6c, 0xd5, 0xf2, 0xf0, 0x85, 0xce, 0x72, 0x09, 0x33, 0xe6, 0x5c, 0xe9, 0xa8, 0x55,
	0x2f, 0x72, 0x53, 0xed, 0x7e, 0x21, 0xb0, 0xbf, 0x00, 0x31, 0x89, 0x92, 0x06, 0x29, 0x85, 0x46,
	0xa8, 0x22, 0x2c, 0x31, 0xf9, 0x33, 0xdd, 0x83, 0x65, 0x63, 0x99, 0x4d, 0x4d, 0x49, 0x29, 0x15,
	0x6d, 0xc1, 0xca, 0x18, 0x8d, 0x61, 0x1c, 0x4b, 0xc4, 0x54, 0xd2, 0xbb, 0xd0, 0x88, 0x98, 0x65,
	0xad, 0x86, 0x43, 0x0e, 0xd6, 0xfb, 0xfb, 0xdd, 0x49, 0xaf, 0xfb, 0x94, 0x59, 0x36, 0xa5, 0x4c,
	0xa1, 0x79, 0x91, 0xdb, 0x83, 0x9d, 0x4b, 0x92, 0x95, 0xe9, 0x48, 0x75, 0x3a, 0xf7, 0x35, 0x6c,
	0x3c, 0x57, 0x5c, 0xc8, 0xab, 0xf7, 0xe6, 0x03, 0x81, 0xcd, 0xf2, 0xaf, 0xaf, 0xd4, 0x91, 0x3b,
	0x15, 0x47, 0xae, 0xcd, 0x3b, 0x52, 0x20, 0x0b, 0x3f, 0x3e, 0x12, 0xd8, 0x5e, 0xc8, 0xd1, 0x5d,
	0x58, 0xb2, 0xea, 0x0c, 0x65, 0xd9, 0x47, 0x21, 0xb2, 0x51, 0x84, 0x39, 0x09, 0xad, 0x98, 0x14,
	0x63, 0xae, 0x06, 0x17, 0xba, 0x62, 0x41, 0x7d, 0xce, 0x82, 0x9b, 0x00, 0xb1, 0xe2, 0x1c, 0xa3,
	0x97, 0x62, 0x8c, 0x79, 0x53, 0x6b, 0xc1, 0x4c, 0xc4, 0xbd, 0x05, 0xeb, 0x45, 0x0b, 0x85, 0xbf,
	0xbb, 0xb0, 0x34, 0xc2, 0x38, 0x56, 0x53, 0x78, 0x2e, 0xdc, 0xdb, 0xb0, 0x31, 0xdb, 0x67, 0xe6,
	0x8a, 0x4a, 0x6d, 0x92, 0xda, 0xb2, 0xac, 0x54, 0xfd, 0x1f, 0x35, 0xd8, 0x78, 0x65, 0x50, 0xbf,
	0x28, 0x3f, 0x1d, 0xfa, 0x99, 0xc0, 0xd6, 0xdc, 0x02, 0xd2, 0x76, 0x66, 0xc9, 0xe5, 0xab, 0xdf,
	0xbe, 0x7e, 0x69, 0xae, 0xa0, 0xba, 0x0f, 0x3e, 0xfd, 0xfc, 0xf3, 0xad, 0xd6, 0x77, 0x3d, 0x7f,
	0xd2, 0xf3, 0x2b, 0x9f, 0xa8, 0xaf, 0xcb, 0x23, 0x1e, 0x2b, 0xce, 0x78, 0x23, 0xa6, 0x27, 0x68,
	0xac, 0x90, 0x7c, 0x40, 0x3a, 0xf4, 0xb4, 0xdc, 0xa2, 0x69, 0x0b, 0xcd, 0x0c, 0x33, 0xbb, 0x57,
	0xed, 0xed, 0x99, 0x48, 0x89, 0xbb, 0x9f, 0xe3, 0x7c, 0xb7, 0xb3, 0x88, 0x8b, 0xb3, 0xc2, 0xff,
	0xb0, 0x9e, 0xc1, 0x6a, 0xe6, 0xd5, 0x13, 0x35, 0x64, 0x74, 0xeb, 0xdf, 0xdb, 0x2f, 0x30, 0xcd,
	0xf9, 0x75, 0x70, 0x5b, 0x39, 0x85, 0xba, 0x9b, 0x19, 0x25, 0x41, 0x1d, 0xaa, 0x21, 0x63, 0x72,
	0x40, 0x3a, 0x8f, 0x7f, 0x93, 0xaf, 0x27, 0xbf, 0x08, 0xd5, 0xb0, 0x59, 0x81, 0xbb, 0x6f, 0xe6,
	0x02, 0xf4, 0x68, 0x64, 0x6d, 0x62, 0x06, 0xbe, 0xcf, 0x85, 0x1d, 0xa5, 0xc3, 0x6e, 0xa8, 0xc6,
	0x7e, 0x24, 0xc2, 0xb3, 0xf7, 0x1c, 0x35, 0x8b, 0x23, 0xe1, 0xe7, 0x17, 0x8e, 0x57, 0x39, 0xd4,
	0xde, 0x9b, 0xad, 0x78, 0xc4, 0xc7, 0x4c, 0xc4, 0xd9, 0xc1, 0x7e, 0xbd, 0xd7, 0x3d, 0xec, 0x10,
	0xd2, 0x6f, 0xb2, 0x24, 0x89, 0x45, 0x98, 0x5f, 0x59, 0xfe, 0xa9, 0x51, 0x72, 0xb0, 0x10, 0x09,
	0x1e, 0x42, 0xfd, 0xf8, 0xf0, 0x98, 0x1e, 0x43, 0x27, 0x40, 0x9b, 0x6a, 0x89, 0x91, 0x73, 0x3e,
	0x42, 0xe9, 0xd8, 0x11, 0x3a, 0x1a, 0x8d, 0x4a, 0x75, 0x88, 0x4e, 0xa4, 0xd0, 0x38, 0x52, 0x59,
	0x07, 0xdf, 0x09, 0x63, 0xbb, 0x74, 0x19, 0x1a, 0xdf, 0x6b, 0x64, 0x65, 0xb8, 0x9c, 0x77, 0x75,
	0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xde, 0x60, 0xed, 0x6d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServicesClient is the client API for UserServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServicesClient interface {
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
	LoginAccount(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	DataCoba(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type userServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServicesClient(cc grpc.ClientConnInterface) UserServicesClient {
	return &userServicesClient{cc}
}

func (c *userServicesClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, "/v1.UserServices/RegisterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServicesClient) LoginAccount(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/v1.UserServices/LoginAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServicesClient) DataCoba(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/v1.UserServices/DataCoba", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServicesServer is the server API for UserServices service.
type UserServicesServer interface {
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
	LoginAccount(context.Context, *LoginRequest) (*LoginResponse, error)
	DataCoba(context.Context, *DataRequest) (*DataResponse, error)
}

// UnimplementedUserServicesServer can be embedded to have forward compatible implementations.
type UnimplementedUserServicesServer struct {
}

func (*UnimplementedUserServicesServer) RegisterAccount(ctx context.Context, req *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}
func (*UnimplementedUserServicesServer) LoginAccount(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccount not implemented")
}
func (*UnimplementedUserServicesServer) DataCoba(ctx context.Context, req *DataRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataCoba not implemented")
}

func RegisterUserServicesServer(s *grpc.Server, srv UserServicesServer) {
	s.RegisterService(&_UserServices_serviceDesc, srv)
}

func _UserServices_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServicesServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserServices/RegisterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServicesServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServices_LoginAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServicesServer).LoginAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserServices/LoginAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServicesServer).LoginAccount(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServices_DataCoba_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServicesServer).DataCoba(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserServices/DataCoba",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServicesServer).DataCoba(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserServices",
	HandlerType: (*UserServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAccount",
			Handler:    _UserServices_RegisterAccount_Handler,
		},
		{
			MethodName: "LoginAccount",
			Handler:    _UserServices_LoginAccount_Handler,
		},
		{
			MethodName: "DataCoba",
			Handler:    _UserServices_DataCoba_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-services.proto",
}
