// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-services.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterAccountRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	NumberPhone          string   `protobuf:"bytes,2,opt,name=numberPhone,proto3" json:"numberPhone,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountRequest) Reset()         { *m = RegisterAccountRequest{} }
func (m *RegisterAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountRequest) ProtoMessage()    {}
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{0}
}

func (m *RegisterAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountRequest.Unmarshal(m, b)
}
func (m *RegisterAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountRequest.Merge(m, src)
}
func (m *RegisterAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountRequest.Size(m)
}
func (m *RegisterAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountRequest proto.InternalMessageInfo

func (m *RegisterAccountRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterAccountRequest) GetNumberPhone() string {
	if m != nil {
		return m.NumberPhone
	}
	return ""
}

func (m *RegisterAccountRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *RegisterAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterAccountResponse struct {
	Code                 string               `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponseAccount `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterAccountResponse) Reset()         { *m = RegisterAccountResponse{} }
func (m *RegisterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountResponse) ProtoMessage()    {}
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{1}
}

func (m *RegisterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountResponse.Unmarshal(m, b)
}
func (m *RegisterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountResponse.Merge(m, src)
}
func (m *RegisterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountResponse.Size(m)
}
func (m *RegisterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountResponse proto.InternalMessageInfo

func (m *RegisterAccountResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RegisterAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegisterAccountResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterAccountResponse) GetData() *DataResponseAccount {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponseAccount struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	LoggedTime           string   `protobuf:"bytes,4,opt,name=loggedTime,proto3" json:"loggedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponseAccount) Reset()         { *m = DataResponseAccount{} }
func (m *DataResponseAccount) String() string { return proto.CompactTextString(m) }
func (*DataResponseAccount) ProtoMessage()    {}
func (*DataResponseAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{2}
}

func (m *DataResponseAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponseAccount.Unmarshal(m, b)
}
func (m *DataResponseAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponseAccount.Marshal(b, m, deterministic)
}
func (m *DataResponseAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponseAccount.Merge(m, src)
}
func (m *DataResponseAccount) XXX_Size() int {
	return xxx_messageInfo_DataResponseAccount.Size(m)
}
func (m *DataResponseAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponseAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponseAccount proto.InternalMessageInfo

func (m *DataResponseAccount) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DataResponseAccount) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *DataResponseAccount) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *DataResponseAccount) GetLoggedTime() string {
	if m != nil {
		return m.LoggedTime
	}
	return ""
}

type LoginAccountRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	NumberPhone          string   `protobuf:"bytes,2,opt,name=numberPhone,proto3" json:"numberPhone,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountRequest) Reset()         { *m = LoginAccountRequest{} }
func (m *LoginAccountRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountRequest) ProtoMessage()    {}
func (*LoginAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{3}
}

func (m *LoginAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountRequest.Unmarshal(m, b)
}
func (m *LoginAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountRequest.Merge(m, src)
}
func (m *LoginAccountRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountRequest.Size(m)
}
func (m *LoginAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountRequest proto.InternalMessageInfo

func (m *LoginAccountRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginAccountRequest) GetNumberPhone() string {
	if m != nil {
		return m.NumberPhone
	}
	return ""
}

func (m *LoginAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAccountResponse struct {
	Code                 string               `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponseAccount `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginAccountResponse) Reset()         { *m = LoginAccountResponse{} }
func (m *LoginAccountResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountResponse) ProtoMessage()    {}
func (*LoginAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c6cf8152457cbc, []int{4}
}

func (m *LoginAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountResponse.Unmarshal(m, b)
}
func (m *LoginAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountResponse.Merge(m, src)
}
func (m *LoginAccountResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountResponse.Size(m)
}
func (m *LoginAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountResponse proto.InternalMessageInfo

func (m *LoginAccountResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LoginAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LoginAccountResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginAccountResponse) GetData() *DataResponseAccount {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterAccountRequest)(nil), "v1.RegisterAccountRequest")
	proto.RegisterType((*RegisterAccountResponse)(nil), "v1.RegisterAccountResponse")
	proto.RegisterType((*DataResponseAccount)(nil), "v1.DataResponseAccount")
	proto.RegisterType((*LoginAccountRequest)(nil), "v1.LoginAccountRequest")
	proto.RegisterType((*LoginAccountResponse)(nil), "v1.LoginAccountResponse")
}

func init() { proto.RegisterFile("user-services.proto", fileDescriptor_40c6cf8152457cbc) }

var fileDescriptor_40c6cf8152457cbc = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xbf, 0x6f, 0xd4, 0x30,
	0x18, 0x95, 0xef, 0x8e, 0xb6, 0xb8, 0x45, 0x54, 0x6e, 0xd5, 0x46, 0x01, 0x41, 0x14, 0x31, 0xa0,
	0x83, 0x24, 0xbd, 0x6b, 0x07, 0x74, 0x2c, 0x14, 0x31, 0x22, 0x84, 0x02, 0x6c, 0x2c, 0x6e, 0xf2,
	0xe1, 0x98, 0x26, 0x76, 0xb0, 0x9d, 0x14, 0x56, 0xe8, 0x82, 0xc4, 0x04, 0x1b, 0xff, 0x16, 0x0b,
	0x03, 0x23, 0x7f, 0x08, 0x8a, 0x2f, 0x39, 0xdd, 0x2f, 0x31, 0x21, 0x31, 0x9d, 0xdf, 0xf7, 0xde,
	0x77, 0xef, 0xf3, 0xb3, 0x1d, 0xbc, 0x57, 0x69, 0x50, 0x81, 0x06, 0x55, 0xf3, 0x04, 0x74, 0x58,
	0x2a, 0x69, 0x24, 0xe9, 0xd5, 0x23, 0xf7, 0x26, 0x93, 0x92, 0xe5, 0x10, 0xd1, 0x92, 0x47, 0x54,
	0x08, 0x69, 0xa8, 0xe1, 0x52, 0xb4, 0x0a, 0xf7, 0xbe, 0xfd, 0x49, 0x02, 0x06, 0x22, 0xd0, 0x17,
	0x94, 0x31, 0x50, 0x91, 0x2c, 0xad, 0x62, 0x55, 0xed, 0x5f, 0x22, 0x7c, 0x10, 0x03, 0xe3, 0xda,
	0x80, 0x3a, 0x4d, 0x12, 0x59, 0x09, 0x13, 0xc3, 0xbb, 0x0a, 0xb4, 0x21, 0xbb, 0xb8, 0x4f, 0x4b,
	0xee, 0x20, 0x0f, 0xdd, 0xbd, 0x1a, 0x37, 0x4b, 0xe2, 0xe1, 0x6d, 0x51, 0x15, 0x67, 0xa0, 0x9e,
	0x67, 0x52, 0x80, 0xd3, 0xb3, 0xcc, 0x7c, 0x89, 0xb8, 0x78, 0xeb, 0x4d, 0x95, 0xe7, 0xcf, 0x68,
	0x01, 0x4e, 0xdf, 0xd2, 0x33, 0xdc, 0x70, 0x25, 0xd5, 0xfa, 0x42, 0xaa, 0xd4, 0x19, 0x4c, 0xb9,
	0x0e, 0xfb, 0x5f, 0x10, 0x3e, 0x5c, 0x19, 0x43, 0x97, 0x52, 0x68, 0x20, 0x04, 0x0f, 0x12, 0x99,
	0x42, 0x3b, 0x88, 0x5d, 0x93, 0x03, 0xbc, 0xa1, 0x0d, 0x35, 0x95, 0x6e, 0x87, 0x68, 0x11, 0x71,
	0xf0, 0x66, 0x01, 0x5a, 0x53, 0xd6, 0xd9, 0x77, 0x90, 0xdc, 0xc3, 0x83, 0x94, 0x1a, 0x6a, 0x9d,
	0xb7, 0xc7, 0x87, 0x61, 0x3d, 0x0a, 0x9f, 0x50, 0x43, 0x3b, 0x97, 0xce, 0xd4, 0x8a, 0xfc, 0x4f,
	0x08, 0xef, 0xad, 0x61, 0xc9, 0x3e, 0xbe, 0x62, 0xe4, 0x39, 0x88, 0x76, 0x96, 0x29, 0x68, 0x36,
	0xc6, 0xf5, 0x69, 0x62, 0x78, 0x3d, 0xcd, 0x64, 0x2b, 0x9e, 0xe1, 0xbf, 0x06, 0x72, 0x0b, 0xe3,
	0x5c, 0x32, 0x06, 0xe9, 0x4b, 0x5e, 0x40, 0x1b, 0xc9, 0x5c, 0xc5, 0x07, 0xbc, 0xf7, 0x54, 0x32,
	0x2e, 0xfe, 0xcd, 0xb9, 0xcc, 0xb2, 0xef, 0x2f, 0x65, 0xff, 0x19, 0xe1, 0xfd, 0x45, 0x9f, 0xff,
	0x16, 0xfc, 0xf8, 0xb2, 0x87, 0x77, 0x5e, 0x69, 0x50, 0x2f, 0xda, 0x5b, 0x4f, 0x2e, 0x11, 0xbe,
	0xbe, 0x74, 0x31, 0x88, 0xdb, 0xfc, 0xc7, 0xfa, 0x4b, 0xeb, 0xde, 0x58, 0xcb, 0x4d, 0xad, 0xfc,
	0x07, 0x1f, 0x7f, 0xfc, 0xfe, 0xd6, 0x1b, 0xfb, 0x41, 0x54, 0x8f, 0xa2, 0x85, 0xd7, 0x15, 0xa9,
	0xb6, 0x25, 0xa0, 0xd3, 0x9e, 0x20, 0xa3, 0xaa, 0x06, 0x6d, 0xb8, 0x60, 0x13, 0x34, 0x24, 0x05,
	0xde, 0x99, 0x8f, 0x88, 0xd8, 0x6d, 0xac, 0x39, 0x1c, 0xd7, 0x59, 0x25, 0x5a, 0xf3, 0xa1, 0x35,
	0xbf, 0xe3, 0xdf, 0x5e, 0x35, 0xcf, 0x1b, 0x7d, 0xe7, 0x3c, 0x41, 0xc3, 0xc7, 0xbf, 0xd0, 0xd7,
	0xd3, 0x9f, 0x88, 0x28, 0x7c, 0x6d, 0x41, 0xe8, 0xbf, 0x5e, 0x2a, 0x90, 0xe3, 0xcc, 0x98, 0x52,
	0x4f, 0xa2, 0x88, 0x71, 0x93, 0x55, 0x67, 0x61, 0x22, 0x8b, 0x28, 0xe5, 0xc9, 0xf9, 0x07, 0x06,
	0x8a, 0xe6, 0x29, 0x8f, 0xec, 0x2b, 0x0f, 0x16, 0x9a, 0xdc, 0x83, 0x79, 0xc5, 0x23, 0x56, 0x50,
	0x9e, 0x37, 0x8d, 0xe3, 0xfe, 0x28, 0x3c, 0x1a, 0x22, 0x34, 0xde, 0xa5, 0x65, 0x99, 0xf3, 0xc4,
	0x7e, 0x27, 0xa2, 0xb7, 0x5a, 0x8a, 0xc9, 0x4a, 0x25, 0x7e, 0x88, 0xfb, 0x27, 0x47, 0x27, 0xe4,
	0x04, 0x0f, 0x63, 0x30, 0x95, 0x12, 0x90, 0x7a, 0x17, 0x19, 0x08, 0xcf, 0x64, 0xe0, 0x29, 0xd0,
	0xb2, 0x52, 0x09, 0x78, 0xa9, 0x04, 0xed, 0x09, 0x69, 0x3c, 0x78, 0xcf, 0xb5, 0x09, 0xc9, 0x06,
	0x1e, 0x7c, 0xef, 0xa1, 0xcd, 0xb3, 0x0d, 0x3b, 0xd5, 0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x9d, 0x92, 0xde, 0xe2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServicesClient is the client API for UserServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServicesClient interface {
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
	LoginAccount(ctx context.Context, in *LoginAccountRequest, opts ...grpc.CallOption) (*LoginAccountResponse, error)
}

type userServicesClient struct {
	cc *grpc.ClientConn
}

func NewUserServicesClient(cc *grpc.ClientConn) UserServicesClient {
	return &userServicesClient{cc}
}

func (c *userServicesClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, "/v1.UserServices/RegisterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServicesClient) LoginAccount(ctx context.Context, in *LoginAccountRequest, opts ...grpc.CallOption) (*LoginAccountResponse, error) {
	out := new(LoginAccountResponse)
	err := c.cc.Invoke(ctx, "/v1.UserServices/LoginAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServicesServer is the server API for UserServices service.
type UserServicesServer interface {
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
	LoginAccount(context.Context, *LoginAccountRequest) (*LoginAccountResponse, error)
}

// UnimplementedUserServicesServer can be embedded to have forward compatible implementations.
type UnimplementedUserServicesServer struct {
}

func (*UnimplementedUserServicesServer) RegisterAccount(ctx context.Context, req *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}
func (*UnimplementedUserServicesServer) LoginAccount(ctx context.Context, req *LoginAccountRequest) (*LoginAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccount not implemented")
}

func RegisterUserServicesServer(s *grpc.Server, srv UserServicesServer) {
	s.RegisterService(&_UserServices_serviceDesc, srv)
}

func _UserServices_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServicesServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserServices/RegisterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServicesServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServices_LoginAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServicesServer).LoginAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserServices/LoginAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServicesServer).LoginAccount(ctx, req.(*LoginAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserServices",
	HandlerType: (*UserServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAccount",
			Handler:    _UserServices_RegisterAccount_Handler,
		},
		{
			MethodName: "LoginAccount",
			Handler:    _UserServices_LoginAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-services.proto",
}
